//
// TinyTypeImplicits.scala
//
// Copyright (c) 2016 by Devshorts, Inc.
//
// This file is autogenerated
//

package io.paradoxical.scala.tiny.data.typetag2

import io.paradoxical.scala.tiny.data.typetag2.TinyType._
object TinyTypeImplicits {
  
    implicit def convertToLongId(rawType: Long): longId = rawType.asInstanceOf[longId]

    implicit def convertToBarId(rawType: Int): barId = rawType.asInstanceOf[barId]
    implicit def convertToBarId(rawType: Integer): barId = rawType.asInstanceOf[barId]

    implicit def convertToFunId(rawType: Int): funId = rawType.asInstanceOf[funId]

    implicit def convertToTableId(rawType: java.util.UUID): tableId = rawType.asInstanceOf[tableId]

    implicit def convertToWorkId(rawType: String): workId = rawType.asInstanceOf[workId]
}